### ISSUE TITLE
"Error; please specify "upload_port"

### ISSUE THREAD

**Issue by azey23** [brettdottech/info-orbs#199]
Error: Please specify `upload_port` for environment or use global `--upload-port` option.
For some development platforms it can be a USB flash drive (i.e. /media/<user>/<device name>)
*** [upload] Explicit exit, status 1

Anyone seen this error before? Cannot find where to specify

**Comment by azey23** [comment]
Thanks Hugo - I still cannot seem to locate this in platformo.ini 

Is there a screenshot anywhere I can use? Thanks

**Comment by HugoBalder** [comment]
You have ro add a new line with upload_port = COM<number> in this section of platformio.ini
<img width="907" alt="image" src="https://github.com/user-attachments/assets/f85e340b-0259-4108-b930-a75fbe48cd14" />

**Comment by azey23** [comment]
Next problem; I don't have usb's numbered in device manager. (COM3, ect) 

I have "Universal Series bus controllers" but they name driver types. 

Is there an alternative solution?

//acer Nitro 5

**Comment by HugoBalder** [comment]
Watch the Youtube Video from Brett and start at Minute 13, there is everything described how to flash and install everything.

**Comment by azey23** [comment]
Yes, didn't help unfortunately. However, I connected USB-C to USB-C and it worked! In case anyone else struggling with this
